#!/usr/bin/env python3
"""
IntakeFormProcessor — Generated by Hybrid Local AI Hub
Model: qwen2.5vl:7b

Instructions:
The agent should continuously monitor the folder ./gym_intake for new PDF files. Upon detecting a new file:
      1. Use `read_file` to read the content of the newly detected PDF.
      2. Extract text from the PDF using an appropriate tool (e.g., PyPDF2 or Tika).
      3. Pass the extracted text to the local LLM for processing: "Call a local Ollama LLM model with the extracted text as input."
      4. The LLM should generate a personalized 4-week workout and nutrition plan based on member's stated goals, fitness level, and any injuries mentioned in the form.
      5. Check if the generated plan mentions "weight loss" as the primary goal: If it does, route the plan to a cardio-focused template; otherwise, route it to a strength-focused template.
      6. Generate an embedding of the intake text using `run_python` with code that uses a suitable library (e.g., SentenceTransformer) and store this embedding in a ChromaDB collection named "gym_members".
      7. Write the generated plan as a markdown file, naming it after the member's name, to ./gym_plans.

Tools: "read_file", "run_python", "call_llm"
"""

import os
import sys
import json
import subprocess
import urllib.request
import urllib.error

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "qwen2.5vl:7b"
TOOLS = ["read_file", "run_python", "call_llm"]

SYSTEM_PROMPT = """The agent should continuously monitor the folder ./gym_intake for new PDF files. Upon detecting a new file:
      1. Use `read_file` to read the content of the newly detected PDF.
      2. Extract text from the PDF using an appropriate tool (e.g., PyPDF2 or Tika).
      3. Pass the extracted text to the local LLM for processing: "Call a local Ollama LLM model with the extracted text as input."
      4. The LLM should generate a personalized 4-week workout and nutrition plan based on member's stated goals, fitness level, and any injuries mentioned in the form.
      5. Check if the generated plan mentions "weight loss" as the primary goal: If it does, route the plan to a cardio-focused template; otherwise, route it to a strength-focused template.
      6. Generate an embedding of the intake text using `run_python` with code that uses a suitable library (e.g., SentenceTransformer) and store this embedding in a ChromaDB collection named "gym_members".
      7. Write the generated plan as a markdown file, naming it after the member's name, to ./gym_plans.

Available tools (use XML format):
<function=read_file><parameter=path>filepath</parameter></function>
<function=write_file><parameter=path>filepath</parameter><parameter=content>text</parameter></function>
<function=list_files><parameter=path>directory</parameter></function>
<function=run_python><parameter=code>python code</parameter></function>
<function=final_answer><parameter=answer>your final answer</parameter></function>
"""

def call_ollama(prompt, system=None):
    payload = {
        "model": MODEL,
        "prompt": prompt,
        "system": system or SYSTEM_PROMPT,
        "stream": False
    }
    data = json.dumps(payload).encode()
    req = urllib.request.Request(
        OLLAMA_URL,
        data=data,
        headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read())
            return result.get("response", "")
    except Exception as e:
        return f"LLM error: {e}"

def execute_tool(tool_name, params):
    if tool_name == "read_file":
        path = params.get("path", "")
        try:
            with open(path, "r", encoding="utf-8") as f:
                return f.read()[:4000]
        except Exception as e:
            return f"Error reading {path}: {e}"

    elif tool_name == "write_file":
        path = params.get("path", "")
        content = params.get("content", "")
        try:
            os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            return f"Written to {path}"
        except Exception as e:
            return f"Error writing {path}: {e}"

    elif tool_name == "list_files":
        path = params.get("path", ".")
        try:
            result = []
            for item in os.listdir(path):
                full = os.path.join(path, item)
                result.append(f"[DIR] {item}/" if os.path.isdir(full) else item)
            return "\n".join(result)
        except Exception as e:
            return f"Error listing {path}: {e}"

    elif tool_name == "run_python":
        code = params.get("code", "")
        try:
            # Write to temp file and execute
            import tempfile
            with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as tf:
                tf.write(code)
                tf_name = tf.name
            proc = subprocess.run(
                [sys.executable, tf_name],
                capture_output=True, text=True, timeout=30
            )
            os.unlink(tf_name)
            status = "SUCCESS" if proc.returncode == 0 else "FAILED"
            return f"[{status}] exit={proc.returncode}:\n{proc.stdout}\n{proc.stderr}"
        except Exception as e:
            return f"Error running Python: {e}"

    elif tool_name == "final_answer":
        return f"FINAL: {params.get('answer', '')}"

    else:
        return f"Unknown tool: {tool_name}"

def parse_xml_tools(text):
    """Parse <function=X><parameter=Y>V</parameter></function> format."""
    calls = []
    i = 0
    while True:
        fn_start = text.find("<function=", i)
        if fn_start == -1:
            break
        name_end = text.find(">", fn_start)
        if name_end == -1:
            break
        tool_name = text[fn_start + len("<function="):name_end].strip()
        fn_end = text.find("</function>", name_end)
        if fn_end == -1:
            break
        inner = text[name_end + 1:fn_end]
        params = {}
        j = 0
        while True:
            p_start = inner.find("<parameter=", j)
            if p_start == -1:
                break
            p_name_end = inner.find(">", p_start)
            if p_name_end == -1:
                break
            p_name = inner[p_start + len("<parameter="):p_name_end].strip()
            p_val_end = inner.find("</parameter>", p_name_end)
            if p_val_end == -1:
                break
            p_val = inner[p_name_end + 1:p_val_end].strip()
            params[p_name] = p_val
            j = p_val_end + len("</parameter>")
        calls.append((tool_name, params))
        i = fn_end + len("</function>")
    return calls

def run_agent(task, max_rounds=10):
    conversation = [f"System:\n{SYSTEM_PROMPT}\n\nUser Task:\n{task}"]
    print(f"\\n🤖 {MODEL} Agent starting task...\\n")

    for round_num in range(max_rounds):
        prompt = "\n\n".join(conversation)
        response = call_ollama(prompt)
        print(f"[Round {round_num + 1}] Agent: {response[:200]}...")

        # Parse and execute tools
        tool_calls = parse_xml_tools(response)
        tool_results = []
        for tool_name, params in tool_calls:
            print(f"  → Tool: {tool_name}({list(params.keys())})")
            result = execute_tool(tool_name, params)
            tool_results.append(f"[{tool_name} result]: {result[:500]}")
            if tool_name == "final_answer":
                print(f"\\n✅ Final Answer: {params.get('answer', result)}")
                return params.get("answer", result)

        msg = f"[Agent Round {round_num + 1}]:\n{response}"
        if tool_results:
            msg += f"\n\nTool Results:\n{chr(10).join(tool_results)}"
        conversation.append(msg)

    return conversation[-1]

if __name__ == "__main__":
    task = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else input("Enter task: ")
    result = run_agent(task)
    print(f"\nResult: {result}")
